UserHome/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.UserHome, name='UserHome'),
    path('shop/', views.shop, name='shop'),
    path('login/', views.signin, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('otp/', views.otp, name='otp'),
    path('product/<int:product_id>/', views.product_details, name='product_details'),
    path('about/', views.about, name='about'),
    path('forgot-password/', views.forgot_password, name='forgot-password'),
    path('otp-new-password/', views.otp_for_new_password, name='otp_for_new_password'),
    path('filter-product/', views.filter_product, name='filter_product'),
    path('cart_available_stock/', views.cart_available_stock, name='cart_available_stock'),
    path('product_details_available_stock/', views.product_details_available_stock, name='product_details_available_stock'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('sort/', views.sort, name='sort'),
    
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UserHome.urls')),
    path('', include('AdminHome.urls')),
    path('', include('admin_product_management.urls')),
    path('', include('user_profile.urls')),
    path('', include('user_product.urls')),
    path('', include('user_order.urls')),
    path('', include('admin_order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_order/urls.py
from django.urls import path
from . import views

app_name='user_order'

urlpatterns = [

    path('checkout_details/<int:cart_id>/', views.checkout_details, name='checkout_details'),
    path('checkout_payment/', views.checkout_payment, name='checkout_payment'),
    path('checkout_complete/', views.checkout_complete, name='checkout_complete'),
    path('order_view/<int:order_id>/', views.order_view, name='order_view'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/failure/', views.payment_failure, name='payment_failure'),
    path('razorpay-checkout/', views.razorpay_checkout, name='razorpay_checkout'),

    path('cod-payment/', views.cod_payment, name='cod_payment'),
    path('razorpay-payment/', views.razorpay_payment, name='razorpay_payment'),
    path('wallet-payment/', views.wallet_payment, name='wallet_payment'),
    path('payment/pending/', views.payment_pending, name='payment_pending'),

    path('payment/complete-pending/<int:order_item_id>', views.complete_pending_payment, name='complete_pending_payment'),
    path('cod-payment/pending', views.pending_cod_payment, name='pending_cod_payment'),
    path('razorpay-payment/pending', views.pending_razorpay_payment, name='pending_razorpay_payment'),
    path('razorpay-checkout/pending', views.pending_razorpay_checkout, name='pending_razorpay_checkout'),
    path('wallet-payment/pending', views.pending_wallet_payment, name='pending_wallet_payment'),
    path('payment/pending/pending', views.pending_payment_pending, name='pending_payment_pending'),
    path('payment/pending/complete', views.pending_payment_complete, name='pending_payment_complete'),
    path('payment/pending/failure', views.pending_payment_failure, name='pending_payment_failure'),

    path('delivery-charge/', views.apply_delivery_charge, name='apply_delivery_charge'),
    path('delivery-charge/remove/', views.remove_delivery_charge, name='remove_delivery_charge'),

]

user_profile/urls.py
from django.urls import path
from django.shortcuts import render, redirect
from . import views

app_name='user_profile'

urlpatterns = [
    path('account/', views.account, name='account'),
    path('orders/', views.orders, name='orders'),

    path('addresses/', views.addresses, name='addresses'),
    path('addresses/add', views.add_address, name='add_address'),
    path('addresses/delete/<int:address_id>/', views.delete_address, name='delete_address'),
    path('addresses/edit/<int:address_id>/', views.edit_address, name='edit_address'),
    path('addresses/is_shipping/<int:address_id>/', views.is_shipping, name='is_shipping'),

    path('user/account/edit', views.edit_profile, name='edit_profile'),
    path('user/account/change-password', views.change_password, name='change_password'),

    path('order-tracking/', views.order_tracking, name='order_tracking'),
    path('all_order_items/', views.all_order_items, name='all_order_items'),
    path('cancel_order_item/<int:order_item_id>', views.cancel_order_item, name='cancel_order_item'),

    path('print-invoice/<int:order_item_id>/', views.print_invoice, name='print_invoice'),

    path('wallet/', views.wallet, name='wallet'),
    path('wallet/add/', views.add_to_wallet, name='add_to_wallet'),
    path('razorpay-wallet/', views.razorpay_wallet, name='razorpay_wallet'),
    path('razorpay-wallet/add/', views.razorpay_add_to_wallet, name='razorpay_add_to_wallet'),
    path('wallet/withdraw/', views.withdraw_from_wallet, name='withdraw_from_wallet'),
    path('wallet/withdrw/', views.withdraw_from_wallet_view, name='withdraw_from_wallet_view'),
    path('transaction-history/', views.transaction_history, name='transaction_history'),

    path('user/coupon/', views.coupon, name='coupon'),
    path('referal', views.generate_referral_code, name='generate_referral_code'),
    path('referal/apply', views.apply_referral, name='apply_referral'),

]

user_profile/forms.py
from django import forms
from .models import UserAddresses
from UserHome.models import UserProfile
from user_order.models import OrderItem

class AddressForm(forms.ModelForm):
    class Meta:
        model = UserAddresses
        fields = "__all__"
        exclude = ['user', 'is_shipping']

        widgets = {
        'full_name': forms.TextInput(attrs={'class': 'form-control rounded'}),
        'street_address': forms.TextInput(attrs={'class': 'form-control rounded'}),
        'city': forms.TextInput(attrs={'class': 'form-control rounded'}),
        'district': forms.TextInput(attrs={'class': 'form-control rounded'}),
        'state': forms.TextInput(attrs={'class': 'form-control rounded'}),
        'pincode': forms.TextInput(attrs={'class': 'form-control rounded'}),

    }

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name', 'phone_number')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control rounded'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control rounded'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control rounded'}),
        }

        required = ['first_name']    

class TrackOrderForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ('tracking_number',)
        widgets = {
            'tracking_number': forms.TextInput(attrs={'class': 'form-control rounded'}),
        }

user_profile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib.auth.forms import PasswordChangeForm
from admin_product_management.models import Coupon, UserCoupon
from UserHome.models import UserProfile
from .forms import AddressForm, ProfileEditForm, TrackOrderForm
from .models import Referral, Transaction, UserAddresses, Wallet
from django.contrib import messages
from user_order.models import Order,OrderAddress, OrderItem, OrderStatus
from django.template.loader import render_to_string
from django.http import HttpResponse, JsonResponse
import razorpay
import os
from dotenv import load_dotenv
import random
import string
from django.db import transaction
from datetime import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

@never_cache
@login_required(login_url='login')
def account(request):
    user = request.user
    return render(request, 'user_profile/account.html', {'user' : user})

@never_cache
@login_required(login_url='login')
def edit_profile(request):
    user = request.user
    form = ProfileEditForm(instance=user)
    if request.method=='POST':
        form = ProfileEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user_profile:account')
    return render(request, 'user_profile/edit_profile.html', {'form' : form})

@never_cache
@login_required(login_url='login')
def change_password(request):
    user = request.user
    form = PasswordChangeForm(user)
    if request.method == 'POST':
        form = PasswordChangeForm(user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your password has been successfully changed.')
            return redirect('user_profile:account')
    return render(request, 'user_profile/change_password.html', {'form': form})

@never_cache
@login_required(login_url='login')
def addresses(request):
    user = request.user
    addresses = UserAddresses.objects.filter(user=user)
    return render(request, 'user_profile/addresses.html', {'addresses' : addresses})

@never_cache
@login_required(login_url='login')
def add_address(request):

    next_page = request.POST.get('next') or request.GET.get('next', 'user_profile:addresses')

    form = AddressForm()
    if request.method == 'POST':
        form = AddressForm(request.POST)
        if form.is_valid():
            address_instance = form.save(commit=False)
            address_instance.user = request.user
            address_instance.save()

            # Redirect to the next page if it's a valid internal URL
            if next_page.startswith('/'):
                return redirect(next_page)
            return redirect('user_profile:addresses')
        else:
            messages.error(request, "Please try again.")
    return render(request, 'user_profile/add_address.html', {
        'form': form,
        'next': next_page 
    })

def is_shipping(request, address_id):
    old_shipping_address = UserAddresses.objects.filter(is_shipping=True).first()

    if old_shipping_address:
        old_shipping_address.is_shipping = False
        old_shipping_address.save()

    address = UserAddresses.objects.get(id=address_id)
    address.is_shipping = True
    address.save()

    return redirect('user_profile:addresses')


def delete_address(request, address_id):
    address = UserAddresses.objects.get(id=address_id)
    address.delete()
    return redirect('user_profile:addresses')

@never_cache
@login_required(login_url='login')
def edit_address(request, address_id):
    address = UserAddresses.objects.get(id=address_id)
    form = AddressForm(instance=address)
    if request.method == 'POST':
        form = AddressForm(request.POST, instance=address)
        if form.is_valid():
            form.save()
            return redirect('user_profile:addresses')
    return render(request, 'user_profile/edit_address.html', {'form' : form})

@never_cache
@login_required(login_url='login')
def orders(request):
    try:
        orders = Order.objects.filter(user=request.user)
    except Order.DoesNotExist:
        return render(request, 'user_profile/empty_orders.html')

    all_order_items = []
    for order in orders:
        order_items = OrderItem.objects.select_related('order').filter(order=order)
        all_order_items.extend(order_items)

    items_per_page = 5
    paginator = Paginator(all_order_items, items_per_page)
    page = request.GET.get('page')

    try:
        order_items = paginator.page(page)
    except PageNotAnInteger:
        order_items = paginator.page(1)
    except EmptyPage:
        order_items = paginator.page(paginator.num_pages)

    return render(request, 'user_profile/orders.html', {'order_items': order_items})

@never_cache
@login_required(login_url='login')
def all_order_items(request):
    try:
        orders = Order.objects.filter(user=request.user)
    except Order.DoesNotExist:
        return render(request, 'user_profile/empty_orders.html')
    
    all_order_items = []
    for order in orders:
        order_items = OrderItem.objects.select_related('order').filter(order=order)
        all_order_items.extend(order_items)

    items_per_page = 5
    paginator = Paginator(all_order_items, items_per_page)
    page = request.GET.get('page')

    try:
        order_items = paginator.page(page)
    except PageNotAnInteger:
        order_items = paginator.page(1)
    except EmptyPage:
        order_items = paginator.page(paginator.num_pages)
        
    return render(request, 'user_profile/all_order_items.html', {'order_items' : order_items,})


def cancel_order_item(request, order_item_id):
    order_item = OrderItem.objects.get(id=order_item_id)
    payment_status = order_item.payment_status
    if payment_status == "Complete":
        wallet = Wallet.objects.get(user=request.user)
        wallet.balance += order_item.sub_total
        wallet.save()
        wallet.update_transaction(order_item.sub_total, type="Refund")
        messages.success(request, "Order Item cancelled and amount refunded to your wallet.")
    else:
        messages.success(request, "Order Item cancelled")
    order_item.order_status = OrderStatus.objects.get(status='Cancelled')
    order_item.save()
    order_item.qty_update_on_cancel()
    return redirect('user_profile:orders')

@never_cache
@login_required(login_url='login')
def order_tracking(request):
    form = TrackOrderForm()
    order_item = None

    if request.method == 'POST':
        form = TrackOrderForm(request.POST)
        if form.is_valid():
            tracking_number = form.cleaned_data['tracking_number']
            try:
                order_item = OrderItem.objects.get(tracking_number=tracking_number)
            except OrderItem.DoesNotExist:
                order_item = "OrderItem not found"

    return render(request, 'user_profile/order_tracking.html', {'form' : form, 'order_item' : order_item})

@never_cache
@login_required(login_url='login')
def print_invoice(request, order_item_id):
    order_item = OrderItem.objects.get(id=order_item_id)
    return render(request, 'user_profile/invoice.html', {'order_item': order_item})

@never_cache
@login_required(login_url='login')
def wallet(request):
    user = request.user
    try:
        wallet = Wallet.objects.get(user=user)
    except Wallet.DoesNotExist:
        wallet = Wallet.objects.create(user=user, balance=0)
    return render(request, 'user_profile/wallet.html', {'wallet': wallet})

@never_cache
@login_required(login_url='login')
def add_to_wallet(request):
    return render(request, 'user_profile/add_to_wallet.html')

@never_cache
@login_required(login_url='login')
def withdraw_from_wallet_view(request):
    return render(request, 'user_profile/withdraw_from_wallet.html')


def razorpay_wallet(request):
    if request.method == 'POST':
        user=request.user
        name=user.first_name
        email=user.email
        phone_no=user.phone_number
        total_amount=int(request.POST.get('amount'))*100

        RAZOR_KEY_ID = os.getenv('RAZOR_KEY_ID')
        RAZOR_KEY_SECRET = os.getenv('RAZOR_KEY_SECRET')

        client = razorpay.Client(auth=(RAZOR_KEY_ID, RAZOR_KEY_SECRET))
            
        payment = client.order.create({'amount': total_amount, 'currency': 'INR', 'payment_capture': 1})

        return JsonResponse({'total_amount':total_amount,'name':name,'email':email,'phone_no':phone_no,'RAZOR_KEY_ID':RAZOR_KEY_ID})


def razorpay_add_to_wallet(request):
    if request.method == 'POST':
        amount = request.POST['amount']
        wallet = Wallet.objects.get(user=request.user)
        amount = int(amount)//100
        wallet.balance += amount
        wallet.save()
        wallet.update_transaction(amount, type="Deposit")
        messages.success(request, 'Amount added successfully!')
        return redirect('user_profile:wallet')

@never_cache
@login_required(login_url='login')
def withdraw_from_wallet(request):
    if request.method == 'POST':
        amount = request.POST['amount']
        wallet = Wallet.objects.get(user=request.user)
        wallet.balance -= int(amount)
        wallet.save()
        wallet.update_transaction(amount, type="Withdraw")
    messages.success(request, 'Amount withdrawn successfully!')
    return redirect('user_profile:wallet')

@never_cache
@login_required(login_url='login') 
def transaction_history(request):
    wallet = Wallet.objects.get(user=request.user)
    transactions = Transaction.objects.filter(wallet=wallet).order_by('-id')

    paginator = Paginator(transactions, 10) 
    page_number = request.GET.get('page')

    try:
        transactions_page = paginator.page(page_number)
    except PageNotAnInteger:
        transactions_page = paginator.page(1)
    except EmptyPage:
        transactions_page = paginator.page(paginator.num_pages)

user_profile/templates/user_profile/addresses.html
{% extends 'UserHome/base.html' %}
{% block title %}Addresses{% endblock %}
{% block content %}
		<!--start page wrapper -->
		<div class="page-wrapper">
			<div class="page-content">
				<!--start breadcrumb-->
				<section class="py-3 border-bottom border-top d-none d-md-flex bg-light">
					<div class="container">
						<div class="page-breadcrumb d-flex align-items-center">
							<h3 class="breadcrumb-title pe-3">Addresses</h3>
							<div class="ms-auto">
								<nav aria-label="breadcrumb">
									<ol class="breadcrumb mb-0 p-0">
										<li class="breadcrumb-item"><a href="javascript:;"><i class="bx bx-home-alt"></i> Home</a>
										</li>
										<li class="breadcrumb-item"><a href="user_profile:account:;">Account</a>
										</li>
										<li class="breadcrumb-item active" aria-current="page">Addresses</li>
									</ol>
								</nav>
							</div>
						</div>
					</div>
				</section>
				<!--end breadcrumb-->
				<!--start shop cart-->
				<section class="py-4">
					<div class="container">
						<h3 class="d-none">Account</h3>
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-lg-4">
										<div class="card shadow-none mb-3 mb-lg-0 border">
											<div class="card-body">
												<div class="list-group list-group-flush">	
													<a href="{% url 'user_profile:account' %}" class="list-group-item d-flex justify-content-between align-items-center bg-transparent">Account Details <i class='bx bx-user-circle fs-5'></i></a>
													<a href="{% url 'user_profile:orders' %}" class="list-group-item d-flex justify-content-between align-items-center bg-transparent">My Orders <i class='bx bx-cart-alt fs-5'></i></a>
													<a href="{% url 'user_profile:addresses' %}" class="list-group-item bg-success d-flex justify-content-between align-items-center text-white">Addresses <i class='bx bx-home-smile fs-5'></i></a>
													<a href="{% url 'user_profile:wallet' %}" class="list-group-item d-flex justify-content-between align-items-center bg-transparent">Wallet <i class='bx bx-wallet fs-5'></i></a>
													<a href="{% url 'user_profile:coupon' %}" class="list-group-item d-flex justify-content-between align-items-center bg-transparent">Coupon and Referral <i class='bx bx-tag fs-5'></i></a>
													<a href="{% url 'logout' %}" class="list-group-item d-flex justify-content-between align-items-center bg-transparent">Logout <i class='bx bx-log-out fs-5'></i></a>
												</div>
											</div>
										</div>
									</div>
									<div class="col-lg-8">
										<div class="card shadow-none border rounded mb-0 p-2 bg-light">
											<div class="card-body">
												<div class="d-flex d-flex justify-content-between">
													<h4 class="mb-4 fw-bold">Saved Addresses</h4>
													<a href="{% url 'user_profile:add_address' %}"><button class="btn bg-success fw-bold text-white rounded" style="font-size: 14px;">+ Add Address</button></a>
												</div>
												
												<div class="row">
													{% for address in addresses %}
													<div class="col-12 col-lg-5 border rounded m-2 pt-2 bg-white">
														{% if address.is_shipping %}
														<h5 class="mb-3 bg-light rounded d-flex justify-content-center py-1">Default Address</h5>
														{% endif %}
														{% if not address.is_shipping %}
															<div class="row">
																<div class="col-md-12 py-2">
																	<div class="form-check mb-2">
																		<a href="{% url 'user_profile:is_shipping' address.id %}">
																				Make this as Default Address
																		</a>
																	</div>
																</div>
																<hr>
															</div>
														{% else %}
														<hr>
														{% endif %}
														<address>
														{{ address.full_name }}<br>
														{{ address.street_address }}<br>
														{{ address.city }}<br>
														{{ address.district }}<br>
														{{ address.state }}<br>
														{{ address.pincode }}<br>
														<hr>
														<div class="row">
															<div class="col-md-6 text-center mt-1">
																<a href="{% url 'user_profile:edit_address' address.id %}" class="btn btn-warning rounded fw-bold px-4" style="font-size: 11px;">Edit</a>
															</div>
															<div class="col-md-6 text-center mt-1">
																<a href="{% url 'user_profile:delete_address' address.id %}" class="btn btn-danger rounded fw-bold px-4" style="font-size: 11px;">Delete</a>
															</div>
														</div>
													</address>
													</div>
													{% endfor %}
												</div>
												<!--end row-->
											</div>
										</div>
									</div>
								</div>
								<!--end row-->
							</div>
						</div>
					</div>
				</section>
				<!--end shop cart-->
			</div>
		</div>
		<!--end page wrapper -->
		{% endblock %}

user_profile/templates/user_profile/orders.html
{% extends 'UserHome/base.html' %}
{% block title %}My Orders{% endblock %}
{% block content %}
		<!--start page wrapper -->
		<div class="page-wrapper">
			<div class="page-content">
				<!--start breadcrumb-->
				<section class="py-3 border-bottom border-top d-none d-md-flex bg-light">
					<div class="container">
						<div class="page-breadcrumb d-flex align-items-center">
							<h3 class="breadcrumb-title pe-3">My Orders</h3>
							<div class="ms-auto">
								<nav aria-label="breadcrumb">
									<ol class="breadcrumb mb-0 p-0">
										<li class="breadcrumb-item"><a href="{% url 'UserHome' %}"><i class="bx bx-home-alt"></i> Home</a>
										</li>
										<li class="breadcrumb-item"><a href="{% url 'user_profile:account' %}">Account</a>
										</li>
										<li class="breadcrumb-item active" aria-current="page">My Orders</li>
									</ol>
								</nav>
							</div>
						</div>
					</div>
				</section>
				<!--end breadcrumb-->
				<!--start shop cart-->
				<section class="py-4">
					<div class="container">
						<h3 class="d-none">Account</h3>
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-lg-3">
										<div class="card shadow-none mb-3 mb-lg-0 border">
											<div class="card-body">
												<div class="list-group list-group-flush">	
													<a href="{% url 'user_profile:account' %}" class="list-group-item d-flex justify-content-between align-items-center bg-transparent">Account Details <i class='bx bx-user-circle fs-5'></i></a>
													<a href="{% url 'user_profile:orders' %}" class="list-group-item d-flex justify-content-between align-items-center bg-success text-white">My Orders <i class='bx bx-cart-alt fs-5'></i></a>
													<a href="{% url 'user_profile:addresses' %}" class="list-group-item d-flex justify-content-between align-items-center bg-transparent">Addresses <i class='bx bx-home-smile fs-5'></i></a>
													<a href="{% url 'user_profile:wallet' %}" class="list-group-item d-flex justify-content-between align-items-center bg-transparent">Wallet <i class='bx bx-wallet fs-5'></i></a>
													<a href="{% url 'user_profile:coupon' %}" class="list-group-item d-flex justify-content-between align-items-center bg-transparent">Coupon and Referral <i class='bx bx-tag fs-5'></i></a>
													<a href="{% url 'logout' %}" class="list-group-item d-flex justify-content-between align-items-center bg-transparent">Logout <i class='bx bx-log-out fs-5'></i></a>
												</div>
											</div>
										</div>
									</div>
									<div class="col-lg-9">
										<div class="card shadow-none mb-0 p-1">
											<div class="card-body p-0">
												<a href="{% url 'user_profile:all_order_items' %}">
													<button class="btn btn-primary btn-sm rounded my-2 fw-bold">
													  <i class='bx bx-detail'></i> Full Order Details
													</button>
												  </a>
												  
												  <a href="{% url 'user_profile:order_tracking' %}">
													<button class="btn btn-danger btn-sm rounded my-2 fw-bold ms-1">
													  <i class='bx bx-trip'></i> Track Order
													</button>
												  </a>
												  
												
												<div class="row">
													<div class="col-12">
														<div class="checkout-review">
															<div class="card rounded shadow-none mb-3 border">
																<div class="card-body bg-light">
																	<h5 class="mb-0">Review Your Order</h5>
																	<hr>
																	<div class="shop-cart-list">
																		{% for item in order_items %}
																		<div class="cart-item row align-items-center rounded">
																			<div class="col-12 col-lg-7">
																				<div class="d-lg-flex align-items-center gap-3">
																					<div class="cart-img text-center text-lg-start">
																						<img src="{{ item.product.thumbnail.url }}" class="img-fluid rounded" style="width: 100px; height: 100px; object-fit: contain; background-color: white;" alt="{{ item.product.name }}">
																					</div>
																					<div class="cart-detail text-center text-lg-start">
																						<p class="mb-1 product-short-name" style="font-size: 13px;">{{ item.product.brand|upper }}</p>
																						<h6 class="mb-0 fw-bold product-short-title" style="font-size: 13px;">{{ item.product.name }}</h6>
																						<p class="mb-0" style="font-size: 12px;">Size: <span>{{ item.product_variant }}</span></p>
																						<div class="product-price d-flex align-items-center justify-content-start gap-2 mt-2">
																							{% if item.product.offer %}
																								<div class="h6 fw-bold" style="font-size: 14px;">₹{{ item.product.display_price }}</div>
																								<div class="h6 fw-light fw-bold text-secondary text-decoration-line-through" style="font-size: 12px;">{{ item.product.formatted_price }}</div>
																								<div class="h6 fw-light fw-bold text-success ms-3" style="font-size: 12px;">{{ item.product.offer.percent }}% off</div>
																							{% else %}
																								<div class="h6 fw-bold" style="font-size: 14px;">₹{{ item.product.display_price }}</div>
																							{% endif %}
																						</div>
																					</div>
																					<div class="cart-action text-center">
																						<div class="row mb-3">
																							<div class="payment-mode">
																								<span class="p">Order Status:</span>
																								<span class="badge rounded-pill bg-{{ item.order_status.color }} w-10">{{ item.order_status.status }}</span>																								
																							</div>
																						</div>
																					</div>
																				</div>
																			</div>
																			<div class="col-12 col-lg-3">
																				<div class="cart-action text-center">
																					<div class="row">
																						<div class="col-6">
																							<div class="subtotal">
																								<p class="mb-0">Quantity</p>
																								<div class="h6 fw-bold" style="font-size: 13px;">{{ item.quantity }}</div>
																							</div>
																						</div>
																						<div class="col-6">
																							<div class="subtotal">
																								<p class="mb-0">Subtotal</p>
																								<div class="h6 fw-bold" style="font-size: 13px;">₹{{ item.sub_total }}</div>
																							</div>
																						</div>
																					</div>
																				</div>
																			</div>
																			<div class="col-12 col-lg-2">
																				<div class="cart-action text-center">
																					<div class="row">
																						<div class="d-flex"> 
																							{% if item.order_status.id != 5 %}
																								{% if item.order_status.id != 4 %}
																								<a href="{% url 'user_profile:cancel_order_item' item.id %}" class="btn btn-danger btn-sm rounded fw-bold" style="font-size: 11px;">Cancel</a>
																								{% endif %}
																							{% endif %}
																						</div>
																					</div>
																				</div>
																			</div>
																		</div>
																		<hr>
																	{% endfor %}

																	<nav aria-label="Page navigation">
																		<ul class="pagination justify-content-center mt-3">
																			{% if order_items.has_previous %}
																				<li class="page-item">
																					<a class="page-link" href="?page=1">&laquo;</a>
																				</li>
																				<li class="page-item">
																					<a class="page-link" href="?page={{ order_items.previous_page_number }}">{{ order_items.previous_page_number }}</a>
																				</li>
																			{% endif %}
																			<li class="page-item active">
																				<a class="page-link" href="?page={{ order_items.number }}">{{ order_items.number }}</a>
																			</li>
																			{% if order_items.has_next %}
																				<li class="page-item">
																					<a class="page-link" href="?page={{ order_items.next_page_number }}">{{ order_items.next_page_number }}</a>
																				</li>
																				<li class="page-item">
																					<a class="page-link" href="?page={{ order_items.paginator.num_pages }}">&raquo;</a>
																				</li>
																			{% endif %}
																		</ul>
																	</nav>
					
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<!--end row-->
							</div>
						</div>
					</div>
				</section>
				<!--end shop cart-->
			</div>
		</div>
		<!--end page wrapper -->
		{% endblock %}