UserHome/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.UserHome, name='UserHome'),
    path('shop/', views.shop, name='shop'),
    path('login/', views.signin, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('otp/', views.otp, name='otp'),
    path('product/<int:product_id>/', views.product_details, name='product_details'),
    path('about/', views.about, name='about'),
    path('forgot-password/', views.forgot_password, name='forgot-password'),
    path('otp-new-password/', views.otp_for_new_password, name='otp_for_new_password'),
    path('filter-product/', views.filter_product, name='filter_product'),
    path('cart_available_stock/', views.cart_available_stock, name='cart_available_stock'),
    path('product_details_available_stock/', views.product_details_available_stock, name='product_details_available_stock'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('sort/', views.sort, name='sort'),
    
    
]

admin_order/urls.py
from django.urls import path
from . import views

app_name='admin_order'

urlpatterns = [

    path('admin-home/orders/', views.orders, name='orders'),
    path('admin-home/order-items/', views.order_items, name='order_items'),
    path('admin-home/view-order/<int:order_id>/', views.view_order, name='view_order'),    

    path('admin-home/order-status/', views.order_status, name='order_status'),
    path('admin-home/order-status/unlisted/', views.unlisted_order_status, name='unlisted_order_status'),
    path('admin-home/order-status//edit/', views.add_order_status, name='add_order_status'),
    path('admin-home/order-status/edit/<int:order_status_id>/', views.edit_order_status, name='edit_order_status'),
    path('admin-home/order-status/unlist/<int:order_status_id>/', views.unlist_order_status, name='unlist_order_status'),
    path('admin-home/order-status/list/<int:order_status_id>/', views.list_order_status, name='list_order_status'),
    path('admin-home/order-items/change-status/<int:order_item_id>/', views.change_order_status, name='change_order_status'),

    path('admin-home/delivery_charge/', views.delivery_charge, name='delivery_charge'),
    path('admin-home/delivery_charge/add', views.add_delivery_charge, name='add_delivery_charge'),
    path('admin-home/delivery_charge/edit/<int:delivery_charge_id>/', views.edit_delivery_charge, name='edit_delivery_charge'),
    path('admin-home/delivery_charge/delete/<int:delivery_charge_id>/', views.delete_delivery_charge, name='delete_delivery_charge'),


]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UserHome.urls')),
    path('', include('AdminHome.urls')),
    path('', include('admin_product_management.urls')),
    path('', include('user_profile.urls')),
    path('', include('user_product.urls')),
    path('', include('user_order.urls')),
    path('', include('admin_order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_order/models.py
from django.db import models

# Create your models here.
class DeliveryCharge(models.Model):
    city = models.CharField(max_length=50)
    amount = models.IntegerField()

admin_order/forms.py
from django import forms
from user_order.models import OrderItem
from .models import DeliveryCharge

class OrderStatusChangeForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ('order_status',)

class DeliveryChargeForm(forms.ModelForm):
    class Meta:
        model = DeliveryCharge
        fields = '__all__'

admin_order/views.py
from django.shortcuts import render, redirect
from user_order.models import Order, OrderAddress, OrderItem, OrderStatus
from user_order.forms import OrderStatusForm
from .forms import OrderStatusChangeForm
from django.contrib.auth.decorators import login_required
from AdminHome.models import DailySales
from datetime import datetime, timedelta
from .models import DeliveryCharge
from .forms import DeliveryChargeForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

@login_required(login_url='AdminHome:login')
def orders(request):
    orders_list = Order.objects.all()
    
    items_per_page = 10
    paginator = Paginator(orders_list, items_per_page)
    page = request.GET.get('page')

    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
        orders = paginator.page(1)
    except EmptyPage:
        orders = paginator.page(paginator.num_pages)

    return render(request, 'admin_order/orders.html', {'orders': orders})


@login_required(login_url='AdminHome:login')
def order_items(request):
    order_items_list = OrderItem.objects.all()
    
    items_per_page = 10
    paginator = Paginator(order_items_list, items_per_page)
    page = request.GET.get('page')

    try:
        order_items = paginator.page(page)
    except PageNotAnInteger:
        order_items = paginator.page(1)
    except EmptyPage:
        order_items = paginator.page(paginator.num_pages)

    return render(request, 'admin_order/order_items.html', {'order_items': order_items})


@login_required(login_url='AdminHome:login')
def view_order(request, order_id):
    order = Order.objects.get(id=order_id)
    order_items = OrderItem.objects.filter(order=order)
    return render(request, 'admin_order/view_order.html', {'order_items' : order_items})

@login_required(login_url='AdminHome:login')
def order_status(request):
    statuses = OrderStatus.objects.filter(is_listed=True)
    return render(request, 'admin_order/order_status.html', {'statuses' : statuses})

@login_required(login_url='AdminHome:login')
def unlisted_order_status(request):
    statuses = OrderStatus.objects.filter(is_listed=False)
    return render(request, 'admin_order/unlisted_order_status.html', {'statuses' : statuses})

@login_required(login_url='AdminHome:login')
def edit_order_status(request, order_status_id):
    status = OrderStatus.objects.get(id=order_status_id)
    form = OrderStatusForm(instance=status)

    if request.method == 'POST':
        form = OrderStatusForm(request.POST, instance=status)
        if form.is_valid():
            form.save()
            return redirect('admin_order:order_status')

    return render(request, 'admin_order/edit_order_status.html', {'form': form})

@login_required(login_url='AdminHome:login')
def add_order_status(request):
    form = OrderStatusForm()
    if request.method == 'POST':
        form = OrderStatusForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_order:order_status')
    return render(request, 'admin_order/add_order_status.html', {'form' : form})


def unlist_order_status(request, order_status_id):
    status = OrderStatus.objects.get(id=order_status_id)
    status.is_listed = False
    status.save()
    return redirect('admin_order:order_status')

def list_order_status(request, order_status_id):
    status = OrderStatus.objects.get(id=order_status_id)
    status.is_listed = True
    status.save()
    return redirect('admin_order:unlisted_order_status')

@login_required(login_url='AdminHome:login')
def change_order_status(request, order_item_id):
    order_item = OrderItem.objects.get(id=order_item_id)
    form = OrderStatusChangeForm(instance=order_item)

    if request.method == 'POST':
        form = OrderStatusChangeForm(request.POST, instance=order_item)
        if form.is_valid():
            form.save()
            order_item = OrderItem.objects.get(id=order_item_id)
            order_item.qty_update_on_cancel()
            order_item.refund_wallet() 
            order_item.add_to_sales_on_deliver()
            order_item.update_delivery_date()
            return redirect('admin_order:order_items')

    return render(request, 'admin_order/change_order_status.html', {'form': form})


@login_required(login_url='AdminHome:login')
def delivery_charge(request):
    delivery_charges = DeliveryCharge.objects.all()
    return render(request, 'admin_order/delivery_charge.html', {'delivery_charges' : delivery_charges})

@login_required(login_url='AdminHome:login')
def add_delivery_charge(request):
    form = DeliveryChargeForm()
    if request.method == 'POST':
        form = DeliveryChargeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_order:delivery_charge')
    return render(request, 'admin_order/add_delivery_charge.html', {'form' : form})

def edit_delivery_charge(request, delivery_charge_id):
    delivery_charge = DeliveryCharge.objects.filter(id=delivery_charge_id).first()
    form = DeliveryChargeForm(instance=delivery_charge)
    if request.method == 'POST':
        form = DeliveryChargeForm(request.POST, instance=delivery_charge)
        if form.is_valid():
            form.save()
            return redirect('admin_order:delivery_charge')
    return render(request, 'admin_order/add_delivery_charge.html', {'form' : form})
     
def delete_delivery_charge(request, delivery_charge_id):
    delivery_charge = DeliveryCharge.objects.filter(id=delivery_charge_id).first()
    delivery_charge.delete()
    return redirect('admin_order:delivery_charge')

admin_order/templates/admin_order/add_delivery_charge.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Add Delivery Charge{% endblock %}

{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h2>Delivery Charge</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Order Management</a></li>
                <li class="breadcrumb-item"><a href="#">Delivery Charge</a></li>
                <li class="breadcrumb-item active"><a href="#">Add Delivery Charge</a></li>
              </ol>
            </nav>
        </div>
        <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Add Delivery Charge Form</h4>
                <div class="table-responsive">
                  <form action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-gradient-info mr-2">Save</button>
                    <a href="{% url 'admin_order:delivery_charge' %}" class="btn btn-gradient-light mr-2">Cancel</a>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
</div>


{% endblock %}

admin_order/templates/admin_order/delivery_charge.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Delivery Charge{% endblock %}

{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h2>Delivery Charge</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Order Management</a></li>
                <li class="breadcrumb-item active"><a href="#">Manage Delivery Charge</a></li>
              </ol>
            </nav>
        </div>
        <a href="{% url 'admin_order:add_delivery_charge' %}" class="btn btn-gradient-info btn-lg mb-3">+ Add City</a>
        <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Available Cities</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>City</th>
                                <th>Charge</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in delivery_charges %}
                            <tr>
                                <td>{{ item.city }}</td>
                                <td>{{ item.amount }}</td>
                                <td class="text-center">
                                    <a href="{% url 'admin_order:edit_delivery_charge' item.id %}" class="btn btn-gradient-primary btn-sm mx-2">Edit</a>
                                    <a href="{% url 'admin_order:delete_delivery_charge' item.id %}" class="btn btn-gradient-danger btn-sm ">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                        

                        </tbody>
                    </table>
                </div>
              </div>
            </div>
          </div>
        </div>
</div>


{% endblock %}

admin_order/templates/admin_order/order_items.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Order Items{% endblock %}


{% block style %}
<style>
  .table thead th {
    border-top: 0;
    border-bottom-width: 1px;
    
}
.table th, .table td {
  padding: 8px
}

</style>
{% endblock %}


{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h2>Order Items</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Order Item Management</a></li>
              </ol>
            </nav>
        </div>
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Products</h4>
                        <div class="table-responsive" style="overflow-x: auto;">
                          <table class="table" border="1" style="border-color: #5050503f; border-radius: 18px; width: 100%;">
                            <thead>
                                <tr>
                                  <th>SL</th>
                                  <th>Image</th>
                                  <th>Order Date</th>
                                  <th id="product_th" style="text-align: center; width: 50px;">Item ID</th>
                                  <th>Size</th>
                                  <th>Quantity</th>
                                  <th>Subtotal</th>
                                  <th>Order<br>Status</th>
                                  <th>Payment<br>Method</th>
                                  <th>Payment<br>Status</th>

                                  <th style="text-align: center;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in order_items %}
                                <tr>
                                  <td>{{ order_items.start_index|add:forloop.counter0 }}</td>
                                    <td><img src="{{ item.product.thumbnail.url }}" class="img-fluid rounded" style="width: 100%; height: 100%; object-fit: contain; background-color: white;" alt=""></td>
                                    <td>{{ item.order.order_date }}</td>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.product_variant }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>{{ item.sub_total }}</td>
                                    <td>
                                        <span class="badge rounded-pill bg-{{ item.order_status.color }} w-10">{{ item.order_status.status }}</span>
                                    </td>
                                    <td>{{ item.payment_method }}</td>
                                    <td>{{ item.payment_status }}</td>
                                    <td>
                                      {% if item.order_status.id == 5 %}
                                        <div class="bg-danger text-white btn-sm mx-1 ">Cancelled</div>
                                      {% elif item.order_status.status == 'Delivered' %}
                                        <div class="bg-success text-white btn-sm mx-1 ">Delivered</div>
                                      {% else %}
                                        <a href="{% url 'admin_order:change_order_status' item.id %}" class="btn btn-gradient-light btn-sm mx-1">Change Status</a>
                                      {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        </div>



                <!-- Pagination -->
                <nav aria-label="Page navigation">
                  <ul class="pagination justify-content-center mt-3">
                      {% if order_items.has_previous %}
                          <li class="page-item">
                              <a class="page-link" href="?page=1">&laquo;</a>
                          </li>
                          <li class="page-item">
                              <a class="page-link" href="?page={{ order_items.previous_page_number }}">{{ order_items.previous_page_number }}</a>
                          </li>
                      {% endif %}
                      <li class="page-item active">
                          <a class="page-link" href="?page={{ order_items.number }}">{{ order_items.number }}</a>
                      </li>
                      {% if order_items.has_next %}
                          <li class="page-item">
                              <a class="page-link" href="?page={{ order_items.next_page_number }}">{{ order_items.next_page_number }}</a>
                          </li>
                          <li class="page-item">
                              <a class="page-link" href="?page={{ order_items.paginator.num_pages }}">&raquo;</a>
                          </li>
                      {% endif %}
                  </ul>
                </nav>


              </div>
            </div>
          </div>
        </div>
</div>
{% endblock %}

admin_order/templates/admin_order/order_status.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Order Status{% endblock %}

{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h2>Order Status</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Order Management</a></li>
                <li class="breadcrumb-item active"><a href="#">Manage Oder Status</a></li>
              </ol>
            </nav>
        </div>
        <a href="{% url 'admin_order:add_order_status' %}" class="btn btn-gradient-info btn-lg mb-3 me-3">+ Add Status</a>
        <a href="{% url 'admin_order:unlisted_order_status' %}" class="btn btn-gradient-dark btn-lg mb-3">Unlisted Statuses</a>
        <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Available Statuses</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Status</th>
                                <th>Color</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for status in statuses %}
                            <tr>
                                <td>{{ status.status }}</td>
                                <td>{{ status.color }}</td>
                                <td class="text-center">
                                    <a href="{% url 'admin_order:edit_order_status' status.id %}" class="btn btn-gradient-primary btn-sm mx-2">Edit</a>
                                    <a href="{% url 'admin_order:unlist_order_status' status.id %}" class="btn btn-gradient-dark btn-sm ">Unlist</a>
                                </td>
                            </tr>
                        {% endfor %}
                        

                        </tbody>
                    </table>
                </div>
              </div>
            </div>
          </div>
        </div>
</div>


{% endblock %}

admin_order/templates/admin_order/orders.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Orders{% endblock %}

{% block content %}
<div class="main-panel">
  <div class="content-wrapper">
      <div class="page-header">
          <h2>Orders</h2>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Order Management</a></li>
            </ol>
          </nav>
      </div>
      <div class="row">
          <div class="col-md-12 grid-margin stretch-card">
              <div class="card">
                  <div class="card-body">
                      <h4 class="card-title">User Orders</h4>
                      <div class="table-responsive">
                          <table class="table">
                              <thead>
                                  <tr>
                                    <th>SL</th>
                                      <th>Order Date</th>
                                      <th>User</th>
                                      <th>Total Amount</th>
                                      <th>Address</th>
                                      <th class="text-center">Action</th>
                                  </tr>
                              </thead>
                              <tbody>
                                  {% for order in orders %}
                                  <tr>
                                    <td>{{ orders.start_index|add:forloop.counter0 }}</td>
                                      <td>{{ order.order_date }}</td>
                                      <td>{{ order.user }}</td>
                                      <td>₹{{ order.total_amount }}</td>
                                      <td>
                                          {{ order.address.full_name }}<br>
                                          {{ order.address.street_address }}<br>
                                          {{ order.address.city }}, {{ order.address.district }}, {{ order.address.state }} - {{ order.address.pincode }}
                                      </td>
                                      <td class="text-center">
                                          <a href="{% url 'admin_order:view_order' order.id %}" class="btn btn-gradient-primary btn-sm mx-2">View</a>
                                          <a href="" class="btn btn-gradient-dark btn-sm ">Cancel</a>
                                      </td>
                                  </tr>
                                  {% endfor %}
                              </tbody>
                          </table>
                      </div>
                      <!-- Pagination -->
                      <nav aria-label="Page navigation">
                          <ul class="pagination justify-content-center">
                              {% if orders.has_previous %}
                                  <li class="page-item">
                                      <a class="page-link" href="?page=1">&laquo;</a>
                                  </li>
                                  <li class="page-item">
                                      <a class="page-link" href="?page={{ orders.previous_page_number }}">{{ orders.previous_page_number }}</a>
                                  </li>
                              {% endif %}
                              <li class="page-item active">
                                  <a class="page-link" href="?page={{ orders.number }}">{{ orders.number }}</a>
                              </li>
                              {% if orders.has_next %}
                                  <li class="page-item">
                                      <a class="page-link" href="?page={{ orders.next_page_number }}">{{ orders.next_page_number }}</a>
                                  </li>
                                  <li class="page-item">
                                      <a class="page-link" href="?page={{ orders.paginator.num_pages }}">&raquo;</a>
                                  </li>
                              {% endif %}
                          </ul>
                      </nav>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>



{% endblock %}

admin_order/templates/admin_order/unlisted_order_status.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Unlisted Order Status{% endblock %}

{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h2>Unlisted Order Status</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Order Management</a></li>
                <li class="breadcrumb-item active"><a href="#">Manage Unlisted Oder Status</a></li>
              </ol>
            </nav>
        </div>
        <a href="{% url 'admin_order:order_status' %}" class="btn btn-gradient-success btn-lg mb-3">Listed Statuses</a>
        <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Unlisted Statuses</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Status</th>
                                <th>Color</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for status in statuses %}
                            <tr>
                                <td>{{ status.status }}</td>
                                <td>{{ status.color }}</td>
                                <td class="text-center">
                                    <a href="{% url 'admin_order:list_order_status' status.id %}" class="btn btn-gradient-success btn-sm ">List</a>
                                </td>
                            </tr>
                        {% endfor %}
                        

                        </tbody>
                    </table>
                </div>
              </div>
            </div>
          </div>
        </div>
</div>


{% endblock %}

admin_order/templates/admin_order/view_order.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}View Order{% endblock %}

{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h2>View Order</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Order Management</a></li>
                <li class="breadcrumb-item"><a href="#">View Order</a></li>
              </ol>
            </nav>
        </div>
        <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">View Order</h4>
                <div class="table-responsive">
                  <table class="table" border="1" style="border-color: #5050503f; border-radius: 18px;">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Order Date</th>
                            <th>Product</th>
                            <th>Size</th>
                            <th>Quantity</th>
                            <th>Subtotal</th>
                            <th>Order Status</th>
                            <th>Payment Method</th>
                            <th>Payment Status</th>
                            <th style="text-align: center;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in order_items %}
                        <tr>
                            <td><img src="{{ item.product.thumbnail.url }}" class="img-fluid rounded" style="width: 100%; height: 100%; object-fit: contain; background-color: white;" alt=""></td>
                            <td>{{ item.order.order_date }}</td>
                            <td>{{ item.product }}</td>
                            <td>{{ item.product_variant }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>{{ item.sub_total }}</td>
                            <td>
                              {% if item.order_status.id == 1 %}
																				<span class="badge rounded-pill bg-warning w-10">{{ item.order_status.status }}</span>
																			{% elif item.order_status.id == 2 %}
																				<span class="badge rounded-pill bg-info w-10">{{ item.order_status.status }}</span>
																			{% elif item.order_status.id == 3 %}
																				<span class="badge rounded-pill bg-primary w-10">{{ item.order_status.status }}</span>
																			{% elif item.order_status.id == 4 %}
																				<span class="badge rounded-pill bg-success w-10">{{ item.order_status.status }}</span>
																			{% else %}
																				<span class="badge rounded-pill bg-danger w-10">{{ item.order_status.status }}</span>
																			{% endif %}
                            </td>
                            <td>{{ item.payment_method }}</td>
                            <td>{{ item.payment_status }}</td>
                            <td>
                              <a href="{% url 'admin_order:change_order_status' item.id %}" class="btn btn-gradient-light btn-sm mx-1">Change Status</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>
              </div>
            </div>
          </div>
        </div>
</div>


{% endblock %}