AdminHome/urls.py
from django.urls import path
from . import views

app_name='AdminHome'
urlpatterns = [
    path('ad-login/', views.login_view, name='login'),
    path('admin-logout/', views.logout_view, name='logout'),
    path('admin-home/', views.home, name='home'),

    path('admin-users/', views.users, name='users'),
    path('admin-user/block/<int:user_id>/', views.block_user, name='block_user'),
    path('admin-user/unblock/<int:user_id>/', views.unblock_user, name='unblock_user'),
    path('admin-user/delete/<int:user_id>/', views.delete_user, name='delete_user'),

    path('admin-banner/', views.banner, name='banner'),
    path('admin-banner/add', views.add_banner, name='add_banner'),
    path('admin-banner/edit/<int:banner_id>/', views.edit_banner, name='edit_banner'),
    path('admin-banner/delete/<int:banner_id>/', views.delete_banner, name='delete_banner'),

    path('admin-daily-sales-page/', views.daily_sales_page, name='daily_sales_page'),
    path('admin-weekly-sales-page/', views.weekly_sales_page, name='weekly_sales_page'),
    path('admin-monthly-sales-page/', views.monthly_sales_page, name='monthly_sales_page'),

    path('admin-daily-sales/', views.daily_sales, name='daily_sales'),
    path('admin-weekly-sales/', views.weekly_sales, name='weekly_sales'),
    path('admin-monthly-sales/', views.monthly_sales, name='monthly_sales'),
    path('admin-sales/', views.sales_report_view, name='sales_report_view'),
    path('admin-sales-from-to/', views.sales_from_to, name='sales_from_to'),
    path('admin-sales-report-print/', views.print_sales_report, name='print_sales_report'),
    
    path('admin-sales-report/excel', views.generate_excel, name='generate_excel'),
    path('admin-sales-report/pdf', views.generate_pdf, name='generate_pdf'),

]

UserHome/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.UserHome, name='UserHome'),
    path('shop/', views.shop, name='shop'),
    path('login/', views.signin, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('otp/', views.otp, name='otp'),
    path('product/<int:product_id>/', views.product_details, name='product_details'),
    path('about/', views.about, name='about'),
    path('forgot-password/', views.forgot_password, name='forgot-password'),
    path('otp-new-password/', views.otp_for_new_password, name='otp_for_new_password'),
    path('filter-product/', views.filter_product, name='filter_product'),
    path('cart_available_stock/', views.cart_available_stock, name='cart_available_stock'),
    path('product_details_available_stock/', views.product_details_available_stock, name='product_details_available_stock'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('sort/', views.sort, name='sort'),
    
    
]

admin_order/urls.py
from django.urls import path
from . import views

app_name='admin_order'

urlpatterns = [

    path('admin-home/orders/', views.orders, name='orders'),
    path('admin-home/order-items/', views.order_items, name='order_items'),
    path('admin-home/view-order/<int:order_id>/', views.view_order, name='view_order'),    

    path('admin-home/order-status/', views.order_status, name='order_status'),
    path('admin-home/order-status/unlisted/', views.unlisted_order_status, name='unlisted_order_status'),
    path('admin-home/order-status//edit/', views.add_order_status, name='add_order_status'),
    path('admin-home/order-status/edit/<int:order_status_id>/', views.edit_order_status, name='edit_order_status'),
    path('admin-home/order-status/unlist/<int:order_status_id>/', views.unlist_order_status, name='unlist_order_status'),
    path('admin-home/order-status/list/<int:order_status_id>/', views.list_order_status, name='list_order_status'),
    path('admin-home/order-items/change-status/<int:order_item_id>/', views.change_order_status, name='change_order_status'),

    path('admin-home/delivery_charge/', views.delivery_charge, name='delivery_charge'),
    path('admin-home/delivery_charge/add', views.add_delivery_charge, name='add_delivery_charge'),
    path('admin-home/delivery_charge/edit/<int:delivery_charge_id>/', views.edit_delivery_charge, name='edit_delivery_charge'),
    path('admin-home/delivery_charge/delete/<int:delivery_charge_id>/', views.delete_delivery_charge, name='delete_delivery_charge'),


]

admin_product_management/urls.py
from django.urls import path
from . import views

app_name='admin_product_management'
urlpatterns = [

    path('admin-category/', views.category, name='category'),
    path('admin-category/add', views.add_category, name='add_category'),
    path('admin-category/unlisted', views.unlisted_categories, name='unlisted_categories'),
    path('admin-category/edit/<int:category_id>/', views.edit_category, name='edit_category'),
    path('admin-category/list/<int:category_id>/', views.list_category, name='list_category'),    
    path('admin-category/unlist/<int:category_id>/', views.unlist_category, name='unlist_category'),

    path('admin-brand/', views.brand, name='brand'),
    path('admin-brand/add', views.add_brand, name='add_brand'),
    path('admin-brand/edit/<int:brand_id>/', views.edit_brand, name='edit_brand'),
    path('admin-brand/unlisted', views.unlisted_brands, name='unlisted_brands'),    
    path('admin-brand/list/<int:brand_id>/', views.list_brand, name='list_brand'),    
    path('admin-brand/unlist/<int:brand_id>/', views.unlist_brand, name='unlist_brand'),    

    path('admin-product/', views.product, name='product'),
    path('admin-product/add', views.add_product, name='add_product'),
    path('admin-product/view/<int:product_id>/', views.view_product, name='view_product'),
    path('admin-product/edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('admin-product/delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('admin-product/deleted/', views.deleted_product, name='deleted_product'),
    path('admin-product/restore/<int:product_id>/', views.restore_product, name='restore_product'),

    path('admin-product/image/delete/<int:image_id>/', views.delete_image, name='delete_image'),

    path('admin-product_variant/add/<int:product_id>/', views.add_product_variant, name='add_product_variant'),
    path('admin-product_variant/edit/<int:product_variant_id>/', views.edit_product_variant, name='edit_product_variant'),
    path('admin-product_variant/delete/<int:product_variant_id>/', views.delete_product_variant, name='delete_product_variant'),

    path('admin-offer/add/<int:product_id>/', views.add_offer, name='add_offer'),
    path('admin-offer/edit/<int:offer_id>/', views.edit_offer, name='edit_offer'),
    path('admin-offer/delete/<int:offer_id>/', views.delete_offer, name='delete_offer'),
    
    path('admin-coupon/', views.coupon, name='coupon'),
    path('admin-coupon/add', views.add_coupon, name='add_coupon'),
    path('admin-coupon/edit/<int:coupon_id>/', views.edit_coupon, name='edit_coupon'),
    path('admin-coupon/activate/<int:coupon_id>/', views.activate_coupon, name='activate_coupon'),
    path('admin-coupon/deactivate/<int:coupon_id>/', views.deactivate_coupon, name='deactivate_coupon'),
    path('admin-coupon/deactivated', views.deactivated_coupons, name='deactivated_coupons'),
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UserHome.urls')),
    path('', include('AdminHome.urls')),
    path('', include('admin_product_management.urls')),
    path('', include('user_profile.urls')),
    path('', include('user_product.urls')),
    path('', include('user_order.urls')),
    path('', include('admin_order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AdminHome/models.py
from django.db import models

from admin_product_management.models import Product

class Admin(models.Model):
    name = models.CharField(max_length=50)
    username = models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    email = models.CharField(max_length=100)  
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Banner(models.Model):
    image = models.ImageField(upload_to='banner_image/')
    heading = models.CharField(max_length=200)
    description = models.CharField()
    start_date = models.DateField()
    end_date = models.DateField()

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name
    
class DailySales(models.Model):
    date = models.DateField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    amount = models.IntegerField()

    def __str__(self):
        return f"Daily Sales - {self.date}"

AdminHome/forms.py
from django import forms
from AdminHome.models import Banner

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class BannerForm(forms.ModelForm):
    class Meta:
        model = Banner
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
            'start_date': forms.DateInput(format='%d-%m-%Y', attrs={'type': 'date'}),
            'end_date': forms.DateInput(format='%d-%m-%Y', attrs={'type': 'date'}),
        }

AdminHome/templates/AdminHome/add_banner.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Add Banner{% endblock %}

{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h2>Add Category</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Banner Management</a></li>
                <li class="breadcrumb-item active" aria-current="page">Add Banner</li>
              </ol>
            </nav>
        </div>
        <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Banner Form</h4>
                <p class="card-description"> Add the name, image and description for your Banner </p>
                <form class="forms-sample" method="post" id="myForm" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                                    
                    <button type="submit" class="btn btn-gradient-info mr-2">Add</button>
                    <button class="btn btn-gradient-dark mr-2" type="button" onclick="clearForm()">Clear</button>
                    <a href="{% url 'AdminHome:banner' %}" class="btn btn-gradient-light mr-2">Cancel</a>

                </form>
              </div>
            </div>
          </div>
        </div>
</div>
<script>
    function clearForm() {
        document.getElementById("myForm").reset();
    }
</script>

{% endblock %}

AdminHome/templates/AdminHome/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Admin{% endblock %}</title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'Admin/assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'Admin/assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'Admin/assets/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'Admin/assets/images/favicon.ico' %}" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@700&display=swap" rel="stylesheet">
    <style>
      body * {
        font-family: 'Nunito', sans-serif;
    }
    
      .btn {
        font-family: 'Nunito', sans-serif;
    }

      .badge {
        font-family: 'Nunito', sans-serif;
        color: white;
    }

      th {
        font-family: 'Nunito', sans-serif !important;
    }

      h1, h2, h3, h4, h5, h6 {
        font-family: 'Nunito', sans-serif !important;
    }

    
      /* Center align the content */
      .center-content {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          height: 100vh; /* Adjust the height as needed */
      }

      /* Alert messages */
      .messages {
          position: fixed;
          top: 20px;
          left: 50%;
          transform: translateX(-50%);
          z-index: 1000;
      }

      .alert {
          width: 600px; /* Set width as needed */
      }

      /* Add spacing between elements */
      .content-spacing {
          margin-bottom: 20px; /* Adjust margin as needed */
      }

      @media (max-width: 768px) {
        .alert {
            width: 90%; /* Set a percentage width for smaller screens */
            max-width: 400px; /* Set a maximum width for smaller screens */
        }
    }

  </style>
  {% block style %}
    {% endblock %}
    {% block head %}
    {% endblock %}
</head>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Success:</strong> {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Error:</strong> {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
    {% endfor %}
</ul>
{% endif %}
<body>
  <div class="container-scroller">
    <!-- partial:../../partials/_navbar.html -->
    <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo"><img src="{% static 'Admin/assets/images/brand.jpg' %}" class="rounded" style="height: 45px; width: auto;" alt="logo" /></a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-stretch">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
          <span class="mdi mdi-menu"></span>
        </button>
        <div class="search-field d-none d-md-block">
          
        </div>
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item nav-profile dropdown">
            <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <div class="nav-profile-img">
                <span class="availability-status online"></span>
              </div>
              <div class="nav-profile-text">
                <span class="font-weight-bold text-uppercase">{{ admin_username }}</span>
              </div>
            </a>
            <div class="dropdown-menu navbar-dropdown bg-dark" aria-labelledby="profileDropdown">
              <div class="dropdown-divider"></div>
              <a class="dropdown-item text-white fw-bold bg-dark rounded" href="{% url 'AdminHome:logout' %}">
                <i class="mdi mdi-logout mr-2"></i> Signout </a>
            </div>
          </li>
          
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:../../partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
              <div class="nav-profile-image" style="width: 40px; height: 40px; border-radius: 50%; overflow: hidden; position: relative;">
                <img src="{% static 'Admin\assets\images\faces\f.jpg' %}" alt="Admin Image" style="width: 100%; height: 100%; object-fit: cover;">              </div>
              
              <div class="nav-profile-text d-flex flex-column">
                <span class="font-weight-bold mb-1 text-uppercase">{{ admin_username }}</span>
                <span class="text-secondary text-small">Administrator</span>
              </div>
              <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
          </li>          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'AdminHome:home' %}">
              <span class="menu-title">Dashboard</span>
              <i class="mdi mdi-home menu-icon"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'AdminHome:users' %}">
              <span class="menu-title">User Management</span>
              <i class="mdi mdi-account-multiple menu-icon"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <span class="menu-title">Product Management</span>
              <i class="menu-arrow"></i>
              <i class="mdi mdi-package-variant menu-icon"></i>
            </a>
            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'admin_product_management:category' %}">Manage Category</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'admin_product_management:brand' %}">Manage Brand</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'admin_product_management:product' %}">Manage Product</a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin_product_management:coupon' %}">
              <span class="menu-title">Coupon Management</span>
              <i class="mdi mdi-ticket menu-icon"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'AdminHome:banner' %}">
              <span class="menu-title">Banner Management</span>
              <i class="mdi mdi-image  menu-icon"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#general-pages" aria-expanded="false" aria-controls="general-pages">
              <span class="menu-title">Order And Payments</span>
              <i class="menu-arrow"></i>
              <i class="mdi mdi-cart menu-icon"></i>
            </a>
            <div class="collapse" id="general-pages">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'admin_order:orders' %}"> Manage Orders </a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'admin_order:order_items' %}"> Manage Order Items </a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'admin_order:order_status' %}"> Manage Order Status </a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'admin_order:delivery_charge' %}"> Manage Delivery Charge </a></li>
            </div>
          </li>
        </ul>
      </nav>
      <!-- partial -->
        <!-- content-wrapper ends -->

        {% block content %}
        
        {% endblock %}

       
        </div>
        </div>
        </div>
        </div>
        <script src="{% static 'Admin/assets/vendors/js/vendor.bundle.base.js' %}"></script>
        <script src="{% static 'Admin/assets/js/off-canvas.js' %}"></script>
        <script src="{% static 'Admin/assets/js/hoverable-collapse.js' %}"></script>
        <script src="{% static 'Admin/assets/js/misc.js' %}"></script>

        <!-- Your SweetAlert2 Toast configuration -->
<script>
  {% if messages %}
      {% for message in messages %}
          const Toast = Swal.mixin({
              toast: true,
              position: "top",
              showConfirmButton: false,
              timer: 3000,
              timerProgressBar: true,
              didOpen: (toast) => {
                  toast.onmouseenter = Swal.stopTimer;
                  toast.onmouseleave = Swal.resumeTimer;
              }
          });
          Toast.fire({
              icon: "{{ message.tags }}",  // You might need to map Django message tags to SweetAlert2 icons
              title: "{{ message }}"
          });
      {% endfor %}
  {% endif %}
</script>
        
        {% block script %}
        
        {% endblock %}

</body>
</html>

AdminHome/templates/AdminHome/daily_sales.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Daily Sales{% endblock %}

{% block style %}


{% endblock %}

{% block content %}

        <div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h2 class="page-title"> Daily Sales </h2>
              <a href="{% url 'AdminHome:home' %}"><button class="btn btn-gradient-dark btn-md rounded">Back to Dashboard</button></a>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Admin Home</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                  <li class="breadcrumb-item active" aria-current="page">Daily Sales Report</li>
                </ol>
              </nav>
            </div>
            <div class="row">
                <div class="col-md-4 stretch-card grid-margin">
                  <div class="card bg-gradient-danger card-img-holder text-white">
                    <a href="{% url 'AdminHome:daily_sales_page' %}" class="text-decoration-none text-white">
                      <div class="card-body">
                        <img src="{% static 'Admin/assets/images/dashboard/circle.svg' %}" class="card-img-absolute" alt="circle-image" />
                        <h4 class="font-weight-normal mb-3">Daily Sales Chart<i class="mdi mdi-chart-line mdi-24px float-right"></i>
                        </h4>
                      </div>
                    </div>                    
                    </a>
                  </div>
                  <div class="col-md-4 stretch-card grid-margin">
                    <div class="card bg-gradient-info card-img-holder text-white">
                      <a href="{% url 'AdminHome:weekly_sales_page' %}" class="text-decoration-none text-white">
                      <div class="card-body">
                        <img src="{% static 'Admin/assets/images/dashboard/circle.svg' %}" class="card-img-absolute" alt="circle-image" />
                        <h4 class="font-weight-normal mb-3">Weekly Sales Chart<i class="mdi mdi-chart-areaspline mdi-24px float-right"></i>
                        </h4>
                      </div>
                    </div>
                  </a>
                  </div>
                  <div class="col-md-4 stretch-card grid-margin">
                    <div class="card bg-gradient-success card-img-holder text-white">
                      <a href="{% url 'AdminHome:monthly_sales_page' %}" class="text-decoration-none text-white">
                      <div class="card-body">
                        <img src="{% static 'Admin/assets/images/dashboard/circle.svg' %}" class="card-img-absolute" alt="circle-image" />
                        <h4 class="font-weight-normal mb-3">Monthly Sales Chart<i class="mdi mdi-chart-bar mdi-24px float-right"></i>
                        </h4>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="row">
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Daily Sales Report</h4>
                            <canvas id="dailySalesChart" style="height:230px"></canvas>
                        </div>
                    </div>
                </div>
              </div>


            </div>
          </div>
        </div>
      </div>
    </div>
    

    {% endblock %}

    {% block script %}
    <script src="{% static 'Admin/assets/vendors/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'Admin/assets/js/chart.js' %}"></script>

    <script>
        fetch('/admin-daily-sales/') 
        .then(response => response.json())
        .then(data => {
            const dates = data.dates;
            const sales = data.sales;

            const ctx = document.getElementById('dailySalesChart').getContext('2d');
            const dailySalesChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: dates,
                    datasets: [{
                        label: 'Daily Sales',
                        data: sales,
                        backgroundColor: 'rgba(255, 99, 71, 0.5)',
                        borderColor: 'rgba(255, 99, 71, 1)', 
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        });
    </script>
  
    {% endblock %}

AdminHome/templates/AdminHome/monthly_sales.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Monthly Sales{% endblock %}

{% block style %}


{% endblock %}

{% block content %}

        <div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h2 class="page-title"> Monthly Sales </h2>
              <a href="{% url 'AdminHome:home' %}"><button class="btn btn-gradient-dark btn-md rounded">Back to Dashboard</button></a>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Admin Home</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                  <li class="breadcrumb-item active" aria-current="page">Monthly Sales Report</li>
                </ol>
              </nav>
            </div>
            <div class="row">
                <div class="col-md-4 stretch-card grid-margin">
                  <div class="card bg-gradient-danger card-img-holder text-white">
                    <a href="{% url 'AdminHome:daily_sales_page' %}" class="text-decoration-none text-white">
                      <div class="card-body">
                        <img src="{% static 'Admin/assets/images/dashboard/circle.svg' %}" class="card-img-absolute" alt="circle-image" />
                        <h4 class="font-weight-normal mb-3">Daily Sales Chart<i class="mdi mdi-chart-line mdi-24px float-right"></i>
                        </h4>
                      </div>
                    </div>                    
                    </a>
                  </div>
                  <div class="col-md-4 stretch-card grid-margin">
                    <div class="card bg-gradient-info card-img-holder text-white">
                      <a href="{% url 'AdminHome:weekly_sales_page' %}" class="text-decoration-none text-white">
                      <div class="card-body">
                        <img src="{% static 'Admin/assets/images/dashboard/circle.svg' %}" class="card-img-absolute" alt="circle-image" />
                        <h4 class="font-weight-normal mb-3">Weekly Sales Chart<i class="mdi mdi-chart-areaspline mdi-24px float-right"></i>
                        </h4>
                      </div>
                    </div>
                  </a>
                  </div>
                  <div class="col-md-4 stretch-card grid-margin">
                    <div class="card bg-gradient-success card-img-holder text-white">
                      <a href="{% url 'AdminHome:monthly_sales_page' %}" class="text-decoration-none text-white">
                      <div class="card-body">
                        <img src="{% static 'Admin/assets/images/dashboard/circle.svg' %}" class="card-img-absolute" alt="circle-image" />
                        <h4 class="font-weight-normal mb-3">Monthly Sales Chart<i class="mdi mdi-chart-bar mdi-24px float-right"></i>
                        </h4>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="row">
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Monthly Sales Report</h4>
                            <canvas id="monthlySalesChart" style="height:230px"></canvas>
                        </div>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    

    {% endblock %}

    {% block script %}
    <script src="{% static 'Admin/assets/vendors/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'Admin/assets/js/chart.js' %}"></script>

    <script>
        fetch('/admin-monthly-sales/')  // Assuming this URL corresponds to your Django view
        .then(response => response.json())
        .then(data => {
            const dates = data.dates;
            const sales = data.sales;

            // Render the bar chart using Chart.js
            const ctx = document.getElementById('monthlySalesChart').getContext('2d');
            const dailySalesChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: dates,
                    datasets: [{
                        label: 'Monthly Sales',
                        data: sales,
                        backgroundColor: 'rgba(0, 204, 153, 0.5)',
                        borderColor: 'rgba(0, 204, 153, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        });
    </script>
  
    {% endblock %}