AdminHome/urls.py
from django.urls import path
from . import views

app_name='AdminHome'
urlpatterns = [
    path('ad-login/', views.login_view, name='login'),
    path('admin-logout/', views.logout_view, name='logout'),
    path('admin-home/', views.home, name='home'),

    path('admin-users/', views.users, name='users'),
    path('admin-user/block/<int:user_id>/', views.block_user, name='block_user'),
    path('admin-user/unblock/<int:user_id>/', views.unblock_user, name='unblock_user'),
    path('admin-user/delete/<int:user_id>/', views.delete_user, name='delete_user'),

    path('admin-banner/', views.banner, name='banner'),
    path('admin-banner/add', views.add_banner, name='add_banner'),
    path('admin-banner/edit/<int:banner_id>/', views.edit_banner, name='edit_banner'),
    path('admin-banner/delete/<int:banner_id>/', views.delete_banner, name='delete_banner'),

    path('admin-daily-sales-page/', views.daily_sales_page, name='daily_sales_page'),
    path('admin-weekly-sales-page/', views.weekly_sales_page, name='weekly_sales_page'),
    path('admin-monthly-sales-page/', views.monthly_sales_page, name='monthly_sales_page'),

    path('admin-daily-sales/', views.daily_sales, name='daily_sales'),
    path('admin-weekly-sales/', views.weekly_sales, name='weekly_sales'),
    path('admin-monthly-sales/', views.monthly_sales, name='monthly_sales'),
    path('admin-sales/', views.sales_report_view, name='sales_report_view'),
    path('admin-sales-from-to/', views.sales_from_to, name='sales_from_to'),
    path('admin-sales-report-print/', views.print_sales_report, name='print_sales_report'),
    
    path('admin-sales-report/excel', views.generate_excel, name='generate_excel'),
    path('admin-sales-report/pdf', views.generate_pdf, name='generate_pdf'),

]

UserHome/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.UserHome, name='UserHome'),
    path('shop/', views.shop, name='shop'),
    path('login/', views.signin, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('otp/', views.otp, name='otp'),
    path('product/<int:product_id>/', views.product_details, name='product_details'),
    path('about/', views.about, name='about'),
    path('forgot-password/', views.forgot_password, name='forgot-password'),
    path('otp-new-password/', views.otp_for_new_password, name='otp_for_new_password'),
    path('filter-product/', views.filter_product, name='filter_product'),
    path('cart_available_stock/', views.cart_available_stock, name='cart_available_stock'),
    path('product_details_available_stock/', views.product_details_available_stock, name='product_details_available_stock'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('sort/', views.sort, name='sort'),
    
    
]

admin_product_management/urls.py
from django.urls import path
from . import views

app_name='admin_product_management'
urlpatterns = [

    path('admin-category/', views.category, name='category'),
    path('admin-category/add', views.add_category, name='add_category'),
    path('admin-category/unlisted', views.unlisted_categories, name='unlisted_categories'),
    path('admin-category/edit/<int:category_id>/', views.edit_category, name='edit_category'),
    path('admin-category/list/<int:category_id>/', views.list_category, name='list_category'),    
    path('admin-category/unlist/<int:category_id>/', views.unlist_category, name='unlist_category'),

    path('admin-brand/', views.brand, name='brand'),
    path('admin-brand/add', views.add_brand, name='add_brand'),
    path('admin-brand/edit/<int:brand_id>/', views.edit_brand, name='edit_brand'),
    path('admin-brand/unlisted', views.unlisted_brands, name='unlisted_brands'),    
    path('admin-brand/list/<int:brand_id>/', views.list_brand, name='list_brand'),    
    path('admin-brand/unlist/<int:brand_id>/', views.unlist_brand, name='unlist_brand'),    

    path('admin-product/', views.product, name='product'),
    path('admin-product/add', views.add_product, name='add_product'),
    path('admin-product/view/<int:product_id>/', views.view_product, name='view_product'),
    path('admin-product/edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('admin-product/delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('admin-product/deleted/', views.deleted_product, name='deleted_product'),
    path('admin-product/restore/<int:product_id>/', views.restore_product, name='restore_product'),

    path('admin-product/image/delete/<int:image_id>/', views.delete_image, name='delete_image'),

    path('admin-product_variant/add/<int:product_id>/', views.add_product_variant, name='add_product_variant'),
    path('admin-product_variant/edit/<int:product_variant_id>/', views.edit_product_variant, name='edit_product_variant'),
    path('admin-product_variant/delete/<int:product_variant_id>/', views.delete_product_variant, name='delete_product_variant'),

    path('admin-offer/add/<int:product_id>/', views.add_offer, name='add_offer'),
    path('admin-offer/edit/<int:offer_id>/', views.edit_offer, name='edit_offer'),
    path('admin-offer/delete/<int:offer_id>/', views.delete_offer, name='delete_offer'),
    
    path('admin-coupon/', views.coupon, name='coupon'),
    path('admin-coupon/add', views.add_coupon, name='add_coupon'),
    path('admin-coupon/edit/<int:coupon_id>/', views.edit_coupon, name='edit_coupon'),
    path('admin-coupon/activate/<int:coupon_id>/', views.activate_coupon, name='activate_coupon'),
    path('admin-coupon/deactivate/<int:coupon_id>/', views.deactivate_coupon, name='deactivate_coupon'),
    path('admin-coupon/deactivated', views.deactivated_coupons, name='deactivated_coupons'),
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UserHome.urls')),
    path('', include('AdminHome.urls')),
    path('', include('admin_product_management.urls')),
    path('', include('user_profile.urls')),
    path('', include('user_product.urls')),
    path('', include('user_order.urls')),
    path('', include('admin_order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_product_management/forms.py
from django import forms
from admin_product_management.models import Category, Brand, Product, ProductVariant, Offer
from admin_product_management.models import Coupon


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
        }

class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = '__all__'

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
        }
        exclude = [
            'is_deleted'
        ]

class ProductVariantForm(forms.ModelForm):
    class Meta:
        model = ProductVariant
        exclude = ['product']
       


class OfferForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = '__all__'
        exclude = [
            'discounted_price'
        ]

class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class CouponForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = '__all__'
        widgets = {
            'expiry_date': forms.DateInput(attrs={'type': 'date'}),
        }

admin_product_management/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
from admin_product_management.models import Coupon
from .forms import CategoryForm, Category, BrandForm, ProductForm, ProductVariantForm, OfferForm, CouponForm
from django.contrib import messages
from .models import Category, Brand, Product, ProductVariant, Offer, ProductImages
from django.db.models import Q, F
from django.views.decorators.cache import never_cache
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# ---BRAND---
@login_required(login_url='AdminHome:login')
def brand(request):
    brands = Brand.objects.filter(is_listed=True)
    return render(request, 'admin_product_management/brand.html', {'brands' : brands})

@login_required(login_url='AdminHome:logi')
def add_brand(request):
    form = BrandForm()
    if request.method == 'POST':
        form = BrandForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Added Brand')
            return JsonResponse({'redirect_url': reverse('admin_product_management:brand')})
        else:
            return JsonResponse({'error': 'Form is not valid'})
    return render(request, 'admin_product_management/add_brand.html', {'form': form})

@login_required(login_url='AdminHome:login')
def edit_brand(request, brand_id):
    brand = get_object_or_404(Brand, pk=brand_id)
    if request.method == 'POST':
        form = BrandForm(request.POST, request.FILES, instance=brand)
        if form.is_valid():
            form.save()
            return redirect('admin_product_management:brand')
    else:
        form = BrandForm(instance=brand)
    return render(request, 'admin_product_management/edit_brand.html', {'form': form, 'brand': brand})

@login_required(login_url='AdminHome:login')
def unlisted_brands(request):
    brands = Brand.objects.filter(is_listed=False)
    return render(request, 'admin_product_management/unlisted_brands.html', {'brands' : brands})

def list_brand(request, brand_id):
    brand = get_object_or_404(Brand, pk=brand_id)
    brand.is_listed = True
    brand.save()
    return redirect('admin_product_management:unlisted_brands')

def unlist_brand(request, brand_id):
    brand = get_object_or_404(Brand, pk=brand_id)
    brand.is_listed = False
    brand.save()
    return redirect('admin_product_management:brand')
# ---CATEGORY---

@login_required(login_url='AdminHome:login')
def category(request):
    categories = Category.objects.filter(is_listed=True)
    return render(request, 'admin_product_management/category.html', {'categories' : categories})

@login_required(login_url='AdminHome:login')
def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Added Category')
            return JsonResponse({'redirect_url': reverse('admin_product_management:category')})
        else:
            return JsonResponse({'error': 'Form is not valid'})

    return render(request, 'admin_product_management/add_category.html', {'form': form})

@login_required(login_url='AdminHome:login')
def edit_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            return redirect('admin_product_management:category')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'admin_product_management/edit_category.html', {'form': form, 'category': category})

@login_required(login_url='AdminHome:login')
def unlisted_categories(request):
    categories = Category.objects.filter(is_listed=False)
    return render(request, 'admin_product_management/unlisted_categories.html', {'categories' : categories})

def list_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    category.is_listed = True
    category.save()
    return redirect('admin_product_management:unlisted_categories')

def unlist_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    category.is_listed = False
    category.save()
    return redirect('admin_product_management:category')
# ---PRODUCT---

from django.db.models import Q

@login_required(login_url='AdminHome:login')
def product(request):

    query = request.GET.get('q')
    products = Product.objects.filter(is_listed=True)

    if query:
        products = products.filter(
            Q(name__icontains=query) |
            Q(brand__name__icontains=query) |
            Q(category__name__icontains=query) |
            Q(color__icontains=query)
        )

    for product in products:
        product.offer = Offer.objects.filter(product=product).first()
        product.variants = ProductVariant.objects.filter(product=product)

    paginator = Paginator(products, 5)
    page_number = request.GET.get('page')
    try:
        paginated_objects = paginator.page(page_number)
    except PageNotAnInteger:
        paginated_objects = paginator.page(1)
    except EmptyPage:
        paginated_objects = paginator.page(paginator.num_pages)


    return render(request, 'admin_product_management/product.html', {'paginated_objects': paginated_objects})


@login_required(login_url='AdminHome:login')
def add_product(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            new_product = form.save()
            product_images = request.FILES.getlist('images')
            if product_images:
                for img in product_images:
                    ProductImages.objects.create(product=new_product, images = img)
            return JsonResponse({'redirect_url': reverse('admin_product_management:product')})
        else:
            return JsonResponse({'error': 'Form is not valid'})
    return render(request, 'admin_product_management/add_product.html', {'form': form})

@login_required(login_url='AdminHome:login')
def edit_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    existing_images = ProductImages.objects.filter(product=product)
    product.variants = ProductVariant.objects.filter(product=product)
    product.offers = Offer.objects.filter(product=product)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            new_product = form.save()
            product_images = request.FILES.getlist('images')
            if product_images:
                for img in product_images:
                    ProductImages.objects.create(product=new_product, images = img)
            return redirect('admin_product_management:product')
        else:
            return JsonResponse({'error': 'Form is not valid'})
    else:
        form = ProductForm(instance=product)
    return render(request, 'admin_product_management/edit_product.html', {
        'form': form,
        'existing_images' : existing_images,
        'product' : product,
         })

@login_required(login_url='AdminHome:login')
def view_product(request, product_id):
    product = Product.objects.get(id=product_id)
    product.offer = Offer.objects.filter(product=product).first()
    product.variants = ProductVariant.objects.filter(product=product)
    product.images = ProductImages.objects.filter(product=product)
    return render(request, 'admin_product_management/view_product.html', {'product' : product})

def delete_product(request, product_id):
    product = Product.objects.get(id=product_id)
    product.is_listed = False
    product.save()
    return redirect('admin_product_management:product')

@login_required(login_url='AdminHome:login')
def deleted_product(request):
    products = Product.objects.filter(is_listed=False)
    return render(request, 'admin_product_management/deleted_product.html', {'products': products})

def restore_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.is_listed=True
    product.save()
    return redirect('admin_product_management:deleted_product')

# ---PRODUCT IMAGE---
def delete_image(request, image_id):
    image_to_delete = ProductImages.objects.get(id=image_id)
    product_id = image_to_delete.product.id
    image_to_delete.delete()
    return redirect(reverse('admin_product_management:edit_product', kwargs={'product_id': product_id}))


# ---PRODUCT VARIENT---

@login_required(login_url='AdminHome:login')
def add_product_variant(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == 'POST':
        form = ProductVariantForm(request.POST)
        if form.is_valid():
            size = form.cleaned_data['size']
            quantity = form.cleaned_data['quantity']
            existing_variant = ProductVariant.objects.filter(size=size, product=product).exists()
            if existing_variant:
                ProductVariant.objects.filter(size=size, product=product).update(quantity=F('quantity') + quantity)
            else:
                instance = form.save(commit=False)
                instance.product = product 
                instance.save()
            return redirect(reverse('admin_product_management:edit_product', kwargs={'product_id': product_id}))
    else:
        form = ProductVariantForm()

    return render(request, 'admin_product_management/add_product_variant.html', {'form': form, 'product': product})

@login_required(login_url='AdminHome:login')
def edit_product_variant(request, product_variant_id):

admin_product_management/templates/admin_product_management/brand.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Brand{% endblock %}

{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h2>Brand</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Product Management</a></li>
                <li class="breadcrumb-item active" aria-current="page">Manage Brand</li>
                <li class="breadcrumb-item active" aria-current="page">Add Brand</li>
              </ol>
            </nav>
        </div>
        <a href="{% url 'admin_product_management:add_brand' %}" class="btn btn-gradient-info btn-lg mb-3 me-3">+ Add Brand</a>
        <a href="{% url 'admin_product_management:unlisted_brands' %}" class="btn btn-gradient-dark btn-lg mb-3">Unlisted Brands</a>

        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Brands</h4>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for brand in brands %}
                                    <tr>
                                        <td ><img src="{{ brand.image.url }}" alt="{{ brand.name }}" style="height: 100px; width:auto"></td>
                                        <td>{{ brand.name }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'admin_product_management:edit_brand' brand.id %}" class="btn btn-gradient-primary btn-sm mx-2">Edit</a>
                                            <a href="{% url 'admin_product_management:unlist_brand' brand.id %}" class="btn btn-gradient-dark btn-sm ">Unlist</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

admin_product_management/templates/admin_product_management/category.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Category{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h2>Category</h2>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Product Management</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Manage Category</li>
                </ol>
            </nav>
        </div>

        <a href="{% url 'admin_product_management:add_category' %}" class="btn btn-gradient-info btn-lg mb-3 me-2">+ Add Category</a>
        <a href="{% url 'admin_product_management:unlisted_categories' %}" class="btn btn-gradient-dark btn-lg mb-3">Unlisted Categories</a>
        
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Categories</h4>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th>Description</th>
                                        <th style="text-align: center;">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for category in categories %}
                                    <tr>
                                        <td ><img src="{{ category.image.url }}" alt="{{ category.name }}" style="height: 100px; width:auto"></td>
                                        <td>{{ category.name }}</td>
                                        <td>
                                            <div class="truncated-description">
                                                {{ category.description | slice:":15" }}
                                                {% if category.description|length > 15 %}
                                                    <span class="expand-description text-primary">...more</span>
                                                    <span class="full-description" style="display: none;">
                                                        {{ category.description | slice:"15:" }}
                                                    </span>
                                                {% endif %}
                                            </div>
                                        </td>
                                        <td style="text-align: center;">
                                            <a href="{% url 'admin_product_management:edit_category' category.id %}" class="btn btn-gradient-primary btn-sm mx-2">Edit</a>
                                            <a href="{% url 'admin_product_management:unlist_category' category.id %}" class="btn btn-gradient-dark btn-sm">Unlist</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>



    </div>
</div>


{% endblock %}

admin_product_management/templates/admin_product_management/edit_product.html
{% extends 'AdminHome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Edit Product{% endblock %}

{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h2>Edit Product</h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Product Management</a></li>
                <li class="breadcrumb-item active" aria-current="page">Manage Product</li>
                <li class="breadcrumb-item active" aria-current="page">Edit Product</li>
              </ol>
            </nav>
        </div>
        <div class="row">
          <div class="col-md-7 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Product Form</h4>
                  <p class="card-description"> Edit the details of your Product </p>
                  <form class="forms-sample" method="post" id="myForm" enctype="multipart/form-data">
                      {% csrf_token %}
                      <img src="{{ product.thumbnail.url }}" alt="Existing Image" class="m-3" style="max-width: 150px;">
                      {{ form|crispy }}
                      <br>
                      <button type="submit" class="btn btn-gradient-info mr-2 mt-2">Save</button>
                      <button class="btn btn-gradient-dark mr-2 mt-2" type="button" onclick="clearForm()">Default</button>
                      <a href="{% url 'admin_product_management:product' %}" class="btn btn-gradient-light mr-2 mt-2">Cancel</a>
  
                  
                </div>
              </div>
            </div>
            <div class="col-md-5 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Product Variant</h4>
                    <a href="{% url 'admin_product_management:add_product_variant' product.id %}" class="btn btn-gradient-info btn-sm mb-3" style="font-size: 13px;">+ Add</a>
                    <table class="border">
                      <tr class="border">
                        <th class="border p-2" style="text-align: center; width:100px; font-size: 14px;">Size</th>
                        <th class="border p-2" style="text-align: center; width:100px; font-size: 14px;">Quantity</th>
                        <th class="border p-2" style="text-align: center; width:170px; font-size: 14px;">Action</th>
                      </tr>
                      {% for product_variant in product.variants %}
                        <tr class="border">
                            <td class="border p-2 text-center">{{ product_variant.size }}</td>
                            <td class="border p-2 text-center">{{ product_variant.quantity }}</td>
                            <td class="border p-2 text-center">
                                <a href="{% url 'admin_product_management:edit_product_variant' product_variant.id %}" class="btn btn-gradient-primary btn-sm" style="font-size: 10px;">Edit</a>
                                <a href="{% url 'admin_product_management:delete_product_variant' product_variant.id %}" class="btn btn-gradient-danger btn-sm" style="font-size: 10px;">Delete</a>
                            </td>
                        </tr>
                      {% endfor %}
                    </table>

                    <div class="border border p-3 rounded mt-3">
                      <h4>Existing Offer</h4>
                      <hr>
                      {% if not product.offers %}
                      <a href="{% url 'admin_product_management:add_offer' product.id %}" class="btn btn-gradient-info btn-sm mb-3" style="font-size: 13px;">+ Add</a>
                      {% endif %}
                      {% if product.offers %}
                      <table class="table">
                        <thead>
                            <tr>
                                <th>Offer Percent</th>
                                <th style="text-align: center;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for offer in product.offers %}
                            <tr>
                                <td>{{ offer.percent }} %</td>
                                <td style="text-align: center;">
                                    <a href="{% url 'admin_product_management:edit_offer' offer.id %}" class="btn btn-gradient-primary btn-sm mx-2">Edit</a>
                                    <a href="{% url 'admin_product_management:delete_offer' offer.id %}" class="btn btn-gradient-danger btn-sm">Delete</a>
                                </td>
                            </tr>
                            {% endfor %}
                        
                        </tbody>
                    </table>
                    <br>
                    {% endif %}
                    </div>

                    <div class="border border p-3 rounded mt-3">
                      <h4>Existing images</h4>
                      <hr>
                    {% for image in existing_images %}
                    <img src="{{ image.images.url }}" alt="Existing Image" class="m-3" style="max-width: 120px;">
                    <a href="{% url 'admin_product_management:delete_image' image.id %}" class="btn btn-gradient-danger btn-sm mr-2">Delete</a>
                    <br>
                    {% endfor %}
                    <br>
                    <label for="image_field" class="my-3">Images*</label>
                    <br>
                    <input type="file" name="images" accept="image/*" multiple class="image_field mb-5">
                    </div>
                  </div>
                </div>
              </div>
            </form>
    </div>
</div>
<script>
    function clearForm() {
        document.getElementById("myForm").reset();
    }
</script>

{% endblock %}